name : Transform F1 Data (dbt)

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
      
jobs:
  run-dbt-models:
    runs-on: ubuntu-latest

    env:
        DBT_TARGET: ci
        AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
        SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
        CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
        CURL_CA_INFO: /etc/ssl/certs/ca-certificates.crt

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with: 
          python-version: '3.12'
      
      - name: Installer les certificats SSL
        run: |
          sudo apt-get update
          sudo apt-get install --reinstall -y ca-certificates
          sudo update-ca-certificates

          sudo mkdir -p /etc/pki/tls/certs
          sudo ln -sf /etc/ssl/certs/ca-certificates.crt \
          /etc/pki/tls/certs/ca-bundle.crt
      
      - name: Installer les dependances
        run: pip install -r requirements.txt
      
      - name: Diagnostiquer le Parquet Bronze Azure
        run: |
          python - <<'PY'
          import io
          import os

          import pyarrow.parquet as pq
          from azure.storage.blob import BlobServiceClient

          connection_string = os.environ["AZURE_STORAGE_CONNECTION_STRING"]

          blob_service_client = BlobServiceClient.from_connection_string(
              connection_string
          )

          blob_client = blob_service_client.get_blob_client(
              container="bronze",
              blob="drivers/drivers_latest.parquet"
          )

          properties = blob_client.get_blob_properties()

          print("=== BLOB BRONZE AZURE ===")
          print(f"Nom : {blob_client.blob_name}")
          print(f"Taille : {properties.size} octets")
          print(f"Dernière modification : {properties.last_modified}")
          print(f"ETag : {properties.etag}")

          parquet_bytes = blob_client.download_blob().readall()

          parquet_file = pq.ParquetFile(io.BytesIO(parquet_bytes))

          print("\n=== SCHÉMA PARQUET ===")
          print(parquet_file.schema_arrow)

          table = parquet_file.read()
          dataframe = table.to_pandas()

          print("\n=== COLONNES ===")
          print(dataframe.columns.tolist())

          print("\n=== 5 PREMIÈRES LIGNES ===")
          print(dataframe.head().to_string(index=False))
          PY

      - name: Verifier la configuration dbt
        working-directory: ./f1_transform
        run: dbt debug --profiles-dir . --target ci
      
      - name: Construire et tester les tables
        run: |
          cd f1_transform
          dbt build --profiles-dir . --target ci

          